### ISSUE TITLE
test one image give one error

### ISSUE THREAD

**Issue by alexliyang** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#11]
Thank you open your source, I test the model ,but get the following error:

TypeError: conv_transpose2d(): argument 'output_padding' (position 6) must be tuple of ints, not tuple

**Comment by Intsigstephon** [comment]
> 

if i use pytorch1.12.1  the same error occur which maybe caused by version compatibility files； could you tell me how to modify the source code?
