### ISSUE TITLE
请问下，能否提供一下作者的数据集SDSRD的下载地址，或者合成数据的脚本？我一直没有找到在哪里下载，谢谢！

### ISSUE THREAD

**Issue by cjt222** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#18]

**Comment by JasonLeeFdu** [comment]
Probably 没有或者不公开

**Comment by igodogi** [comment]
你好，请问找到相关方案了吗？可否一起讨论下

**Comment by IsHYuhi** [comment]
Sorry, I'm not the author of this paper. This repository is an "Unofficial" implementation of ''BEDSR-Net: A Deep Shadow Removal from a Single Document Image'' with PyTorch.
So, you can contact the authors.
Thank you.
