### ISSUE TITLE
Could you reopen the [DSRFGD] repositorie?

### ISSUE THREAD

**Issue by igodogi** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#19]
Many thanks for your work.
We are just following your great work of **[DOCUMENT SHADOW REMOVAL WITH FOREGROUND DETECTION LEARNING FROM FULLY SYNTHETIC IMAGES]**. But we can not get access to the code @ **https://github.com/IsHYuhi/DSRFGD** as described in the abstract of the paper.
Could you reopen it or share some other code?

**Comment by IsHYuhi** [comment]
Hi @igodogi ,

I’m sorry for the delayed response.
I had to make it private for a while because I had to reorganize the drive where I keep our data sets.
The repository was opened a few weeks ago. Sorry for the delay.
