### ISSUE TITLE
The code for calculating RMSE, PSNR and SSIM in paper

### ISSUE THREAD

**Issue by lxxcontinue** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#20]
Can I get the code for calculating RMSE, PSNR and SSIM in the paper "DOCUMENT SHADOW REMOVAL WITH FOREGROUND DETECTION LEARNING FROM FULLY SYNTHETIC IMAGES".

**Comment by IsHYuhi** [comment]
https://github.com/IsHYuhi/DSRFGD/issues/4#issuecomment-1463164921
