### ISSUE TITLE
lack of documents

### ISSUE THREAD

**Issue by chenjiefighting** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#4]
Thanks for your work. But some questions occurs when I run the code. I find that /configs is empty, and make_configs.py is not in /utils .

**Comment by IsHYuhi** [comment]
Thank you for opening an issue. I hope  #5 is helpful for you. 

And, I'm going to update this repository step by step, so I recommend you to star this repo. .

Thank you.

**Comment by IsHYuhi** [comment]
Sorry, one thing I forgot to mention is that you need to set ```pretrained: true``` in benet's ```config.yaml```.
